version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: invente25
      POSTGRES_USER: invente25
      POSTGRES_PASSWORD: invente25pw
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d # bind mount the migrations directory to the container so that it runs the migration scripts on startup only once
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U invente25"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build: ./backend
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://invente25:invente25pw@db:5432/invente25
      - JWT_SECRET=supersecret_jwt_here
      - PAYMENT_VERIF_URL=http://payment-verif.local/verify-cash
      - PAYMENT_VERIF_API_KEY=devapikey
      - SYNC_EVENTS_ENABLED=true
      - SYNC_EVENTS_CRON=*/2 * * * * # every 2 minutes and once per startup
      - EVENTS_API_URL=https://ssnsnucinvente.com/api/events
      - PAYMENT_SERVICE_URL=http://localhost:8080/api/payment
      - RECEIPT_SERVICE_URL=http://localhost:8080/api/receipt
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/usr/src/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  db_data:
